package it.elismart_lims.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;

/**
 * Tracks biological sample identity (barcode, matrix, patient/study ID, collection date,
 * and preparation method) for full lot-traceability across experiments.
 *
 * <p>Only {@link MeasurementPair}s of type {@link PairType#SAMPLE} reference a Sample row.
 * All other pair types leave {@code sample_id} null.</p>
 *
 * <p>Audit columns ({@code createdAt}, {@code updatedAt}, {@code createdBy}, {@code updatedBy})
 * are inherited from {@link Auditable} and populated automatically by Spring Data JPA auditing.</p>
 */
@Entity
@Table(name = "sample")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Sample extends Auditable {

    /** Surrogate primary key, auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Unique barcode identifying this sample.
     * Typically a tube or plate barcode scanned at collection time.
     */
    @Column(name = "barcode", nullable = false, unique = true, length = 100)
    private String barcode;

    /**
     * Biological matrix type (e.g. "Serum", "Plasma", "Urine").
     * Nullable — not always known at registration time.
     */
    @Column(name = "matrix_type", length = 100)
    private String matrixType;

    /**
     * Patient or study-subject identifier.
     * Nullable — may be anonymised or omitted for non-clinical studies.
     */
    @Column(name = "patient_id", length = 100)
    private String patientId;

    /**
     * Study or project identifier.
     * Nullable — links the sample to a specific research study.
     */
    @Column(name = "study_id", length = 100)
    private String studyId;

    /**
     * Date on which the sample was collected.
     * Nullable — may be unknown or not relevant for all assay types.
     */
    @Column(name = "collection_date")
    private LocalDate collectionDate;

    /**
     * Free-text description of how the sample was prepared before analysis
     * (e.g. "1:10 dilution in PBS", "heat-inactivated").
     * Nullable.
     */
    @Column(name = "preparation_method", length = 500)
    private String preparationMethod;

    /**
     * Free-text remarks or observations associated with this sample.
     * Nullable.
     */
    @Column(name = "notes", length = 2000)
    private String notes;

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Sample that = (Sample) o;
        return id != null && id.equals(that.id);
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
