-- V14: AI Insight persistence
-- Stores each Gemini analysis call with its question, response, timestamp, and user.
-- The join table ai_insight_experiment links each insight to the experiments it covered.

CREATE TABLE ai_insight (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_question CLOB NOT NULL,
    ai_response   CLOB NOT NULL,
    generated_at  TIMESTAMP NOT NULL,
    generated_by  VARCHAR(100) NOT NULL
);

CREATE TABLE ai_insight_experiment (
    ai_insight_id  BIGINT NOT NULL,
    experiment_id  BIGINT NOT NULL,
    PRIMARY KEY (ai_insight_id, experiment_id),
    CONSTRAINT fk_ai_insight_exp_insight
        FOREIGN KEY (ai_insight_id) REFERENCES ai_insight(id),
    CONSTRAINT fk_ai_insight_exp_experiment
        FOREIGN KEY (experiment_id) REFERENCES experiment(id)
);

CREATE INDEX idx_ai_insight_experiment_exp
    ON ai_insight_experiment (experiment_id);
